"use client";

import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import Image from "next/image";
import { useState } from "react";
import { teachingTopics } from "@/data/teaching";
import { SectionLabel } from "./SectionLabel";

function TopicContent({ index }: { index:number }) {
  if(index===0) return <><h3>Relative Risk, without the jargon.</h3><div className="risk-table" role="table" aria-label="Relative risk example"><div></div><strong>Exposed</strong><strong>Unexposed</strong><span>Develop disease</span><b>20</b><b>10</b><span>No disease</span><b>80</b><b>90</b><span>Total</span><b>100</b><b>100</b></div><div className="equation-row"><span>Risk among exposed<strong>20 / 100 = 0.20</strong></span><span>Risk among unexposed<strong>10 / 100 = 0.10</strong></span><span>Relative Risk<strong>0.20 / 0.10 = 2.0</strong></span></div><p className="lesson-interpretation">The exposed group experienced twice the risk.</p><aside><span>What I want a student to leave with</span>Not just the formula, but the ability to explain what the number means.</aside></>;
  if(index===1) return <><h3>A confidence interval is more than two numbers.</h3><p className="lesson-copy">A point estimate gives us our best single estimate. A confidence interval shows the range of values compatible with the data under the model.</p><div className="number-line" aria-label="Confidence interval illustration"><span className="line-range"/><i/><b>lower range</b><strong>point estimate</strong><b>upper range</b></div><aside><span>The useful idea</span>Uncertainty belongs in the interpretation, not in the fine print.</aside></>;
  if(index===2) return <><h3>What happens after a protocol is approved?</h3><div className="process-mini">{["Screen","Consent","Enroll","Collect","Monitor","Report"].map((item,i)=><span key={item}>{item}{i<5?<i aria-hidden="true">→</i>:null}</span>)}</div><p className="lesson-copy">A clinical trial becomes real through thousands of small operational decisions. Good research depends on each of them being done consistently.</p></>;
  if(index===3) return <><h3>Consent is not a signature.</h3><p className="lesson-copy">Informed consent is a process of communication. The participant should understand what they are being asked to do, why, what the risks are, and that participation is voluntary.</p><div className="ethics-points"><span>Understand</span><span>Ask</span><span>Choose</span></div></>;
  return <><h3>Accuracy is only useful if people can understand it.</h3><div className="plain-language"><div><span>Technical</span><p>“Participants may experience treatment-emergent adverse events.”</p></div><div><span>Plain-language</span><p>“Some people may develop side effects after treatment begins.”</p></div></div><aside><span>The principle</span>Plain language preserves meaning. It does not oversimplify the science.</aside></>;
}

export function Teaching() {
  const [active,setActive]=useState(0);
  const reduced=useReducedMotion();
  return <section id="teaching" className="teaching-section section-pad" aria-labelledby="teaching-title"><div className="wide-shell teaching-layout"><figure className="teaching-image"><div><Image src="/images/diksha_teaching.png" alt="Dr. Diksha Venugopal teaching a class" fill sizes="(max-width: 768px) 100vw, 45vw" /></div><figcaption><span>In the classroom</span>Turning complex ideas into practical, understandable conversations.</figcaption></figure><div className="teaching-main"><div className="section-intro"><SectionLabel>Teaching</SectionLabel><h2 id="teaching-title">Making complex public-health topics easier to understand.</h2><p>The best public-health education should feel useful before the lecture ends.</p></div><p className="topic-instruction">Choose a topic below to see how I would explain it in practice.</p><div className="topic-rail" role="tablist" aria-label="Teaching topics">{teachingTopics.map((topic,index)=><button key={topic} role="tab" aria-selected={active===index} aria-controls="lesson-panel" className={active===index?"is-active":""} onClick={()=>setActive(index)}><span>{String(index+1).padStart(2,"0")}</span>{topic}</button>)}</div><div id="lesson-panel" role="tabpanel" className="lesson-panel"><AnimatePresence mode="wait"><motion.div key={active} initial={reduced?false:{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={reduced?undefined:{opacity:0,y:-8}}><TopicContent index={active}/></motion.div></AnimatePresence></div></div></div></section>;
}
